### ISSUE TITLE
The header Definitions.hpp exists in both qfr and zx projects

### ISSUE THREAD

**Issue by yurivict** [cda-tum/qfr#211]

**Comment by burgholzer** [comment]
Thanks for the interest in our projects and for filing an issue. It would be great if you could provide more context and a proper description for the issues you are facing. Even more so, describe what you would have expected.

It is true, that both libraries contain such a file. However, this is not a problem since the DDPackage file lives under the "dd/" include prefix and, hence, can always be distinguished from the file in the QFR.

**Comment by yurivict** [comment]
Ok, thanks.
